title: Mohammed Ahmed Esmail
description: "A junior machine learning engineer's portfolio"
baseurl: ""
url: "https://yourusername.github.io"
theme: minima

# Social links
github_username: yourusername
linkedin_username: yourlinkedinprofile
