title: Mohammed Ahmed Esmail
logo: /assets/img/head.png
description: "A junior machine learning engineer's portfolio"
#description: text below image
#show_downloads: true
theme: jekyll-theme-minima

# Social links
github_username: yourusername
linkedin_username: yourlinkedinprofile
