title: Mohammed Ahmed
logo: /assets/img/headshot.png
description: "ML engineer"
#show_downloads: true
theme: jekyll-theme-leap-day

# Social links
github_username: MohamedAhmed35
linkedin_username: mu7ammeda7med

