title: Mohammed Ahmed Esmail
description: "A junior machine learning engineer's portfolio"
baseurl: ""
url: "https://yourusername.github.io"
show_downloads: true
theme: jekyll-theme-minimal

# Social links
github_username: yourusername
linkedin_username: yourlinkedinprofile
