title: Mohammed Ahmed
logo: /assets/img/headshot.png
description: "ML engineer"
#description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

# Social links
github_username: yourusername
linkedin_username: [linkedin][LinkedIN-link]

'''
[LinkedIN-link]: https://www.linkedin.com/in/mu7ammeda7med/
