title: Mohammed Ahmed
logo: /assets/img/headshot.png
description: "ML engineer"
description: text below image
#show_downloads: true
theme: jekyll-theme-minimal

# Social links
github_username: MohamedAhmed35
linkedin_username: mu7ammeda7med

